// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import (
	persistence "github.com/gin-tonic/pkg/api/persistence"
	"github.com/gin-tonic/pkg/api/persistence/model"
)

// Persistence is an autogenerated mock type for the Persistence type
type Persistence struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *Persistence) Get(id string) (persistence.Storable, error) {
	args := _m.Called(id)

	var response model.Gintonic

	if args.Get(0) != nil {
		response = args.Get(0).(model.Gintonic)
	}

	return response, args.Error(1)
}

// Save provides a mock function with given fields: r
func (_m *Persistence) Save(r persistence.Storable) error {
	args := _m.Called(r)
	return args.Error(0)
}
