// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/gin-tonic/pkg/api/persistence/model"

// Gintonic is an autogenerated mock type for the Gintonic type
type Gintonic struct {
	mock.Mock
}

// FindGintonic provides a mock function with given fields: id
func (_m *Gintonic) FindGintonic(id string) (model.Gintonic, error) {
	args := _m.Called(id)

	var response model.Gintonic

	if args.Get(0) != nil {
		response = args.Get(0).(model.Gintonic)
	}

	return response, args.Error(1)
}

// SaveGintonic provides a mock function with given fields: _a0
func (_m *Gintonic) SaveGintonic(r model.Gintonic) error {
	args := _m.Called(r)
	return args.Error(0)
}
